version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
  frontend:
    image: fft-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: fft-frontend
    environment:
      - REACT_APP_BACKEND_URL=api
    stdin_open: true
    tty: true
  backend:
    image: fft-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    container_name: fft-backend
